### ISSUE TITLE
Javascript client:  error deployment

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/info_grid#133]
## javascript deployment output

```
➜  grid3_client_ts git:(development) ✗ npx ts-node --project tsconfig-node.json scripts/single_vm.ts
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-06-14 12:21:52        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-06-14 12:21:52        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Key with address: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE is loaded.
Executing method: getTwinIdByAccountId with args: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE
Validation succeed
Executing method: getBalanceOf with args: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE
/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/primitives/nodes.ts:346
        const resources = await this.getNodeFreeResources(nodeId, "zos");
                          ^
Error: Error getting node 4000: Error: Failed to send request to twinId 6260 with command: zos.statistics.get, payload:  due to 401 e2e encryption error: k256: malformed public key
    at /Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/primitives/nodes.ts:253:27
    at async Nodes.nodeHasResources (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/primitives/nodes.ts:346:27)
    at async VMHL.create (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/high_level/machine.ts:61:15)
    at async MachinesModule._createDeployment (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/modules/machines.ts:49:46)
    at async MachinesModule.deploy (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/modules/machines.ts:89:54)
    at async MachinesModule.descriptor.value (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/modules/utils.ts:14:16)
    at async MachinesModule.descriptor.value (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/src/helpers/validator.ts:23:16)
    at async main (/Users/johndoe/code/github/ThreeFoldTech/grid3_client_ts/scripts/single_vm.ts:45:17)
➜  grid3_client_ts git:(development) ✗
```

## config.json content

```
➜  grid3_client_ts git:(development) ✗ more ./scripts/config.json
{
    "network": "main",
    "mnemonic": "<<my_mnemonic>>",
    "storeSecret": "secret",
    "ssh_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAOP0h6VImNcxnIBRMoMfbMfb0xwGHDlaPxZ+nu0CL8ATJekVDHDLMGEPdvACfHBe0sqIw/l6jqoEMR4Dzhjgm4bVEUBVEnG1FvkeNB59sT2DOxDCZuqJvjx2M1bJlH8AR/JQXxUQ+zvfTbavc4/zfCuJm4PYNUsmEt/IQmRwLznGOkoJbwYLhKCC3ykZd0EGpmCWgUUYn0ihaaYkyrliQi5Ny00x0s6jOIJg0CG2Xh5xcrkhOfCZMxZAB+/LGQpZ3tu+Cy5jRf8V/JZ8XQmtYM2GmBUZ1KGcMcsGzrtuudn13JeYLtWJBw6A7Q3Fb7dQSCMLC9UA0uMSZk67M6DFV john@RescuedMac"
}
```

In the manual page there is no explanation what the `storeSecret` has to be.  The error show that the default `secret` is not correct

**Comment by weynandkuijpers** [comment]
Found that `storeSecret` is not the cause for the error: Quote: `Store secret: it's any word that will be used for encrypting/decrypting the keys on threefold key-value store.`

URL: https://threefoldtech.github.io/grid3_client_ts/api/

**Comment by weynandkuijpers** [comment]
Listing existing contracts using the same config file works:
```
➜  grid3_client_ts git:(development) ✗ npx ts-node --project tsconfig-node.json scripts/list_all_contracts.ts
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-06-14 12:34:23        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-06-14 12:34:23        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Key with address: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE is loaded.
Executing method: getTwinIdByAccountId with args: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE
Executing method: getTwinIdByAccountId with args: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE
{
  nameContracts: [],
  nodeContracts: [
    {
      contractID: '40301',
      deploymentData: '{"type":"Fullvm","name":"VM72058b4d","projectName":"Fullvm"}',
      state: 'Created',
      createdAt: '1686041910',
      nodeID: 4000
    }
  ],
  rentContracts: []
}
disconnecting
➜  grid3_client_ts git:(development) ✗
```

**Comment by AhmedHanafy725** [comment]
what is the twin id for this account?

**Comment by Mik-TF** [comment]
Is this issue still relevant?
Can we close it?

@AhmedHanafy725 
@weynandkuijpers 

Thanks!

**Comment by Mik-TF** [comment]
Should be fixed when [this PR](https://github.com/threefoldtech/info_grid/pull/331) is merged.
I simply added the storesecret definition.
Thanks @weynandkuijpers
