### ISSUE TITLE
MANUAL: Javascript client

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/info_grid#138]
Walking through the [javascript client pages(https://www3.manual.grid.tf/javascript/grid3_javascript_loadclient.html)

```
➜  ~ npm --version
8.19.4
➜  ~ node --version
v16.20.0
```
So all version should be good, installed the `--lts` version by using `nvm`

Copied the repo to my local githud directory.  Created a file with what I can load the rewuired data:
```
➜  tests git:(development) ✗ more $HOME/.ssh/mnemonic.tf
export MNEMONICS="<<deleted_mnemonic>>"
export NETWORK="main" # dev, qa or test
export RMB_PROXY="true"
export STORE_SECRET="secret"
export SSH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAOP0h6VImNcxnIBRMoMfbMfb0xwGHDlaPxZ+nu0CL8ATJekVDHDLMGEPdvACfHBe0sqIw/l6jqoEMR4Dzhjgm4bVEUBVEnG1FvkeNB59sT2DOxDCZuqJvjx2M1bJlH8AR/JQXxUQ+zvfTbavc4/zfCuJm4PYNUsmEt/IQmRwLznGOkoJbwYLhKCC3ykZd0EGpmCWgUUYn0ihaaYkyrliQi5Ny00x0s6jOIJg0CG2Xh5xcrkhOfCZMxZAB+/LGQpZ3tu+Cy5jRf8V/JZ8XQmtYM2GmBUZ1KGcMcsGzrtuudn13JeYLtWJBw6A7Q3Fb7dQSCMLC9UA0uMSZk67M6DFV john@RescuedMac"
```

Sourced that dile and hen tried to run the tests: 
```
➜  tests git:(development) ✗ npm run test

> grid3_client@2.1.0-rc2 test
> jest

sh: jest: command not found
```
**So we need to install the `jest` package:**
```
npm install jest
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

added 796 packages, and audited 797 packages in 52s

130 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 high)

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
```

All tests failed:

```
➜  tests git:(development) ✗ npm run test

> grid3_client@2.1.0-rc2 test
> jest

 FAIL  tests/modules/algorand.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/algorand.test.ts:8:1)

 FAIL  tests/modules/stellar.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/stellar.test.ts:8:1)

 FAIL  tests/modules/vm.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/vm.test.ts:2:1)

 FAIL  tests/modules/qsfs.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/qsfs.test.ts:12:1)

 FAIL  tests/modules/kubernetes.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/kubernetes.test.ts:12:1)

 FAIL  tests/modules/gateways.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/gateways.test.ts:2:1)

 FAIL  tests/modules/tfchain.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/tfchain.test.ts:9:1)

 FAIL  tests/modules/contracts.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/contracts.test.ts:12:1)

 FAIL  tests/modules/capacity_planner.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/capacity_planner.test.ts:11:1)

 FAIL  tests/modules/kvstore.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/kvstore.test.ts:2:1)

 FAIL  tests/modules/zdb.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/johndoe/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !storeSecret || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/zdb.test.ts:4:1)

Test Suites: 11 failed, 11 total
Tests:       0 total
Snapshots:   0 total
Time:        149.33 s
```

**Comment by Mik-TF** [comment]
Will be fixed when PR #332 is merged. As for the tests failing, I will make an issue on tfgrid-sdk-ts.

Thanks!
